menu:
  home: /
  archives: /archives
  tags: /tags
  #life: /life
  friends: /cool_guys
  #about: /about

# Place your favicon.ico to /source directory.
favicon: /favicon.ico

# Set default keywords (Use a comma to separate)
keywords: "Hexo,next"

# Set rss to false to disable feed link.
# Leave rss as empty to use site's feed link.
# Set rss to specific value if you have burned your feed already.
rss:

# Icon fonts
# Place your font into next/source/fonts, specify directory-name and font-name here
# Avialable: default | linecons | fifty-shades | feather
#icon_font: default
#icon_font: fifty-shades
#icon_font: feather
#icon_font: linecons
icon_font: love

# Code Highlight theme
# Available value: normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night blue

# Google Analytics
google_analytics: UA-51305142-1
baidu_analytics: 4e150c53fd6e8f77dae864285e0556d5

# MathJax Support
mathjax: true


# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: true


## DO NOT EDIT THE FOLLOWING SETTINGS
## UNLESS YOU KNOW WHAT YOU ARE DOING

# Use velocity to animate everything.
use_motion: true

# Fancybox
fancybox: true

# Static files
vendors: vendors
css: css
images: images

# Theme version
version: 0.3.0rc5
